### PR TITLE
fix issue where locking only happens once per app lifecycle

### LINKED ISSUE #1002: Autolock timer does not work after STR
Build: 1.6.0(3339)
Device: iPhone Xr
iOS: 12.2

Preconditions:
- Biometrics to unlock enabled

Steps to reproduce:
1. Launch Lockwise
2. Unlock Lockwise
3. Lock the device while app is in foreground (wait the amount of time it's need in order for the app to lock)
4. Unlock the device -> The app will be unlocked
5. Backround the app and lock the device
6. Wait the amount of time it's need in order for the app to lock
7. Unlock the device
8. Open the app

Actual results:
- The app will be unlocked.

### PR DESCRIPTION
**Pull request by sashei**
Fixes #1002 

## Testing and Review Notes

The bug description is very useful! This can also be reproduced by simply backgrounding, waiting for the app to lock once, and then trying to get it to lock in the background (NOT hard quitting) a second time.

## To Do

- [x] double check the original issue to confirm it is fully satisfied
- [x] add testing notes and screenshots in PR description to help guide reviewers
- [x] add unit tests
- [ ] make sure CI builds are passing (e.g.: fix lint and other errors)

### CODE REVIEW

File: Shared/Store/BaseDataStore.swift [hunk 1]
```diff
@@ -271,22 +271,25 @@ extension BaseDataStore {
 extension BaseDataStore {
     private func setupAutolock() {
         self.lifecycleStore.lifecycleEvents
-                .filter { $0 == .background }
-                .flatMap { _ in self.storageState }
-                .take(1)
```
Comment (linuxwolf) [inline Shared/Store/BaseDataStore.swift]: TAAAKKE!
