### PR TITLE
autolock respected and reset properly in autofill contexts

### LINKED ISSUE #976: Autofill does not prompt for biometrics when Lockbox is locked
Build: 1.5.0 ( 3240)
Device: iPhone XR
iOS: 12.2

Preconditions:
- Autofill enabled
- Lock Lockbox from Settings

Steps to reproduce:
1. In Firefox or any browser or app, go to a login form
2. Tap on Username field 
3. Tap on the 'Passwords' button above the keyboard

Actual results:
- Lockbox will not prompt for bio metrics. 
- Opening Lockbox after following the STR will not prompt for biometrics.

### LINKED ISSUE #977: Biometrics are not promoted after disabling and enabling Autofill
Build: 1.5.0 ( 3240)
Device: iPhone XR
iOS: 12.2

Preconditions:
- Autofill enabled
- Lock Lockbox from Settings
- Close Lockbox from app switcher

STR:
1. Go to iOS AutoFill Passwords in iOS Settings
2. Disable Autofill
3. Enable Autofill for Lockbox
4. Open Lockbox

Actual results:
- Lockbox is unlocked without biometrics.

[RPReplay_Final1557843446 2.mp4.zip](https://github.com/mozilla-lockwise/lockwise-ios/files/3178211/RPReplay_Final1557843446.2.mp4.zip)

### LINKED ISSUE #982: Respect locked status in the Credential Provider / Autofill
Currently, we don't respect the locked status of the application in the CredentialProvider, including:
- Enabling the credential provider from the Settings
- Accessing a credential via the Quicktype Bar
- Launching the Lockwise list interface from the Quicktype Bar

The current behavior is inconsistent with Android, where we do respect the locked status, and could be confusing for users, particularly in cases where our lenient Autofill lock policy results in Lockwise.app being unlocked when it shouldn't.

This feature tracks including extra unlocking steps in all of the enumerated scenarios when the app is locked, as well as making sure that finishing autofill results in the expected locking behavior back in Lockwise.app or future autofill requests.

Related to #976 
Related to #977

### PR DESCRIPTION
**Pull request by sashei**
Fixes #982 
Fixes #976
Fixes #977 

## Testing and Review Notes
A few things to test here --
- autofill behaves as expected w.r.t. locked status when accessing credentials both via the QTB and the `Passwords` (pop-over list) interfaces, especially using them multiple times in succession as I've already noticed some interesting behavior with the CredentialProvider lifecycle. 
- autofill behaves as expected w.r.t. app authentication and lock status when configuring via settings.
- the way that the locked status of the app interacts with the credential provider. I've made the design choice that unlocking the credential provider will also unlock the app, but it should be locked again when launching after the designated amount of time. 

## To Do

- [x] add “WIP” to the PR title if pushing up but not complete nor ready for review
- [x] double check the original issue to confirm it is fully satisfied
- [x] add testing notes and screenshots in PR description to help guide reviewers
- [x] add unit tests
- [x] make sure CI builds are passing (e.g.: fix lint and other errors)

### CODE REVIEW

File: CredentialProvider/Presenter/CredentialProviderPresenter.swift [hunk 1]
```diff
@@ -126,39 +127,34 @@ class CredentialProviderPresenter {
                         self?.view?.displayWelcome()
                     } else {
                         self?.view?.displayItemList()
-//                        guard let dismissObserver = self?.dismissObserver else { return }
```
Comment (linuxwolf) [inline CredentialProvider/Presenter/CredentialProviderPresenter.swift]: 💯
