### PR TITLE
Fix for Webkit launch crash

### LINKED ISSUE #1147: beginOauthFlow - Lockwise iOS Crashes on launch
There has been a large uptick in crash reports in the new version of Lockwise iOS (1.7.0) that seem to lead back to the `beginOathFlow` Application Services function. Within this update, the app was updated from Xcode 10 to Xcode 11.2.1. The application services framework was updated from v0.32.1 to v0.42.3.

The relevant portion of the crash logs are here:
```
CrashReporter Key:   5d58b0f26a009d004644ffd32b63bbe0af388ee9
Hardware Model:      iPhone11,8
Process:             Firefox Lockbox [23773]
Path:                /private/var/containers/Bundle/Application/7DB9E195-BD96-4D1B-8C51-49708761CBC6/Firefox Lockbox.app/Firefox Lockbox
Identifier:          org.mozilla.ios.Lockbox
Version:             3902 (1.7.0)
AppStoreTools:       11B48b
AppVariant:          1:iPhone11,8:13
Code Type:           ARM-64 (Native)
Role:                Foreground
Parent Process:      launchd [1]
Coalition:           org.mozilla.ios.Lockbox [1016]
Date/Time:           2019-11-25 14:58:48.1907 +0100
Launch Time:         2019-11-25 14:58:46.7381 +0100
OS Version:          iPhone OS 13.2.3 (17B111)
Release Type:        User
Baseband Version:    2.02.12
Report Version:      104
Exception Type:  EXC_BAD_ACCESS (SIGSEGV)
Exception Subtype: KERN_INVALID_ADDRESS at 0x0000000000000000
VM Region Info: 0 is not in any region.  Bytes before following region: 4339351552
      REGION TYPE                      START - END             [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
      UNUSED SPACE AT START
--->  
      __TEXT                 0000000102a54000-0000000102a58000 [   16K] r-x/r-x SM=COW  ...refox Lockbox
Termination Signal: Segmentation fault: 11
Termination Reason: Namespace SIGNAL, Code 0xb
Terminating Process: exc handler [23773]
Triggered by Thread:  0
Thread 0 name:
Thread 0 Crashed:
0   WebKit                        	0x0000000191fe2a58 WTF::Detail::CallableWrapper<WebKit::WebsiteDataStore::fetchDataAndApply(WTF::OptionSet<WebKit::W... + 48 (Function.h:79)
1   JavaScriptCore                	0x00000001996b13a8 WTF::RunLoop::performWork() + 356 (Function.h:79)
2   JavaScriptCore                	0x00000001996b13a8 WTF::RunLoop::performWork() + 356 (Function.h:79)
3   JavaScriptCore                	0x00000001996b1624 WTF::RunLoop::performWork(void*) + 40 (RunLoopCF.cpp:38)
4   CoreFoundation                	0x000000018a50724c __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 28 (CFRunLoop.c:1922)
5   CoreFoundation                	0x000000018a5071a0 __CFRunLoopDoSource0 + 84 (CFRunLoop.c:1956)
6   CoreFoundation                	0x000000018a50690c __CFRunLoopDoSources0 + 184 (CFRunLoop.c:1992)
7   CoreFoundation                	0x000000018a5017d8 __CFRunLoopRun + 1068 (CFRunLoop.c:2882)
8   CoreFoundation                	0x000000018a501084 CFRunLoopRunSpecific + 480 (CFRunLoop.c:3192)
9   GraphicsServices              	0x000000019474f534 GSEventRunModal + 108 (GSEvent.c:2246)
10  UIKitCore                     	0x000000018e671670 UIApplicationMain + 1940 (UIApplication.m:4758)
11  Firefox Lockbox               	0x0000000102a58504 main + 68 (AppDelegate.swift:12)
12  libdyld.dylib                 	0x000000018a380e18 start + 4
Thread 1 name:
Thread 1:
0   libsystem_kernel.dylib        	0x000000018a376ccc __psynch_cvwait + 8
1   libsystem_pthread.dylib       	0x000000018a2994fc _pthread_cond_wait + 680 (pthread_cond.c:591)
2   Firefox Lockbox               	0x0000000102daff30 std::sys::unix::condvar::Condvar::wait_timeout::h08dabe209171db44 + 220 (condvar.rs:157)
3   Firefox Lockbox               	0x0000000102dafbe0 std::thread::park_timeout::h582ababe4c2f3f4c + 356 (condvar.rs:51)
4   Firefox Lockbox               	0x0000000102c312f0 viaduct::backend::send::hab9fc07cb658defb + 9952 (wait.rs:122)
5   Firefox Lockbox               	0x0000000102bb6774 fxa_client::config::Config::remote_config::h3a19bf2f71470689 + 544 (lib.rs:83)
6   Firefox Lockbox               	0x0000000102b93ba8 std::panicking::try::do_call::h26bddc28d50c3df3 + 340 (config.rs:185)
7   Firefox Lockbox               	0x0000000102db4768 __rust_maybe_catch_panic + 36 (lib.rs:80)
8   Firefox Lockbox               	0x0000000102b9a00c fxa_begin_oauth_flow + 188 (panicking.rs:275)
9   Firefox Lockbox               	0x0000000102aef020 closure #1 in FirefoxAccount.beginOAuthFlow(scopes:completionHandler:) + 604 (FirefoxAccount.swift:208)
10  Firefox Lockbox               	0x0000000102a76138 thunk for @escaping @callee_guaranteed () -> () + 28 (<compiler-generated>:0)
11  libdispatch.dylib             	0x000000018a230b7c _dispatch_call_block_and_release + 32 (init.c:1408)
12  libdispatch.dylib             	0x000000018a231fd8 _dispatch_client_callout + 20 (object.m:495)
13  libdispatch.dylib             	0x000000018a238450 _dispatch_lane_serial_drain + 568 (inline_internal.h:2484)
14  libdispatch.dylib             	0x000000018a238e7c _dispatch_lane_invoke + 368 (inline_internal.h:1851)
15  libdispatch.dylib             	0x000000018a241f20 _dispatch_workloop_worker_thread + 580 (queue.c:6445)
16  libsystem_pthread.dylib       	0x000000018a297a94 _pthread_wqthread + 280 (pthread.c:2323)
17  libsystem_pthread.dylib       	0x000000018a29dc7c start_wqthread + 8```

┆Issue is synchronized with this [Jira Story](https://jira.mozilla.com/browse/SYNC-445)

### PR DESCRIPTION
**Pull request by kaylagalway**
Fixes #1147 

The `Dispatcher.register` Observable must be subscribed to on the main thread, otherwise it causes crashes when certain resulting functions are called on background threads. This resolves issue 1147, which was the result of webkit code being called on a background thread when a user's token expires.  

The function that was called on a background thread, causing crashes:
```
/// AccountStore

private func clear() {
        for identifier in KeychainKey.allValues {
            _ = self.keychainWrapper.removeObject(forKey: identifier.rawValue)
        }

       // Crash occurred here
        self.webData.fetchDataRecords(ofTypes: WKWebsiteDataStore.allWebsiteDataTypes()) { records in
            self.webData.removeData(ofTypes: WKWebsiteDataStore.allWebsiteDataTypes(), for: records) { }
        }

        urlCache.removeAllCachedResponses()

        _profile.onNext(nil)
        _syncCredentials.onNext(nil)

        initFxa()
    }
```

Connected to #[Application Services Issue 2279](https://github.com/mozilla/application-services/issues/2279)

### CODE REVIEW

File: lockbox-ios/Store/AccountStore.swift [hunk 1]
```diff
@@ -80,6 +80,7 @@ class AccountStore: BaseAccountStore {
     override func initialized() {
         self.dispatcher.register
                 .filterByType(class: AccountAction.self)
+                .observeOn(MainScheduler.instance)
```
Comment (jhugman) [inline lockbox-ios/Store/AccountStore.swift]: This seems like the simplest fix.

Are the other actions (`oauthLogin`, `oauthSignInMessageRead`) expensive or do any IO traffic? If so, then perhaps an `async` call may be necessary.

Comment (kaylagalway) [reply lockbox-ios/Store/AccountStore.swift]: For the other actions: `oathLogin` calls some asynchronous code that runs on a background thread and `clearOldKeychainValues` needs to be on the main thread because it also calls Webkit functions.
